---
abstract: 'BeLike::KENTNL when you build your distributions.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Capture::Tiny: 0.22
  File::Spec: 0
  File::pushd: 1.005
  FindBin: 0
  Git::Wrapper: 0.030
  IO::Handle: 0
  IPC::Open3: 0
  JSON: 2.59
  Module::Build: 0.4007
  Path::Class: 0.32
  Test::DZil: 4.300039
  Test::Fatal: 0.013
  Test::File::ShareDir: v0.3.3
  Test::More: 0.98
  Test::Output: 1.02
configure_requires:
  Module::Build: 0.4007
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-KENTNL
provides:
  Dist::Zilla::MintingProfile::Author::KENTNL:
    file: lib/Dist/Zilla/MintingProfile/Author/KENTNL.pm
    version: v1.9.0
  Dist::Zilla::Plugin::Author::KENTNL::DistINI:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/DistINI.pm
    version: v1.9.0
  Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/MinimumPerl.pm
    version: v1.9.0
  Dist::Zilla::PluginBundle::Author::KENTNL:
    file: lib/Dist/Zilla/PluginBundle/Author/KENTNL.pm
    version: v1.9.0
requires:
  Carp: 0
  Dist::Zilla: 4.300039
  Dist::Zilla::File::FromCode: 4.300039
  Dist::Zilla::Plugin::Authority: 1.006
  Dist::Zilla::Plugin::AutoPrereqs: 4.300039
  Dist::Zilla::Plugin::Bootstrap::lib: 0.04000001
  Dist::Zilla::Plugin::CheckExtraTests: 0.011
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0.009
  Dist::Zilla::Plugin::ConfirmRelease: 4.300039
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::FakeRelease: 4.300039
  Dist::Zilla::Plugin::FinderCode: 4.300039
  Dist::Zilla::Plugin::Git::Check: 2.014
  Dist::Zilla::Plugin::Git::Commit: 2.014
  Dist::Zilla::Plugin::Git::CommitBuild: 2.014
  Dist::Zilla::Plugin::Git::GatherDir: 2.014
  Dist::Zilla::Plugin::Git::NextVersion: 2.014
  Dist::Zilla::Plugin::Git::Tag: 2.014
  Dist::Zilla::Plugin::GithubMeta: 0.38
  Dist::Zilla::Plugin::License: 4.300039
  Dist::Zilla::Plugin::Manifest: 4.300039
  Dist::Zilla::Plugin::ManifestSkip: 4.300039
  Dist::Zilla::Plugin::MetaConfig: 4.300039
  Dist::Zilla::Plugin::MetaData::BuiltWith: 0.04000000
  Dist::Zilla::Plugin::MetaJSON: 4.300039
  Dist::Zilla::Plugin::MetaProvides: 1.15000000
  Dist::Zilla::Plugin::MetaProvides::Package: 1.15000000
  Dist::Zilla::Plugin::MetaTests: 4.300039
  Dist::Zilla::Plugin::MetaYAML: 4.300039
  Dist::Zilla::Plugin::MinimumPerl: 1.003
  Dist::Zilla::Plugin::ModuleBuild: 4.300039
  Dist::Zilla::Plugin::ModuleShareDirs: 4.300039
  Dist::Zilla::Plugin::NextRelease: 4.300039
  Dist::Zilla::Plugin::PerlTidy: 0.13
  Dist::Zilla::Plugin::PkgVersion: 4.300039
  Dist::Zilla::Plugin::PodCoverageTests: 4.300039
  Dist::Zilla::Plugin::PodSyntaxTests: 4.300039
  Dist::Zilla::Plugin::PodWeaver: 3.102000
  Dist::Zilla::Plugin::Prereqs: 4.300039
  Dist::Zilla::Plugin::Prereqs::MatchInstalled: v0.1.4
  Dist::Zilla::Plugin::Prereqs::MatchInstalled::All: v0.1.2
  Dist::Zilla::Plugin::Prereqs::Plugins: v0.1.3
  Dist::Zilla::Plugin::PruneCruft: 4.300039
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.131500
  Dist::Zilla::Plugin::ReadmeFromPod: 0.18
  Dist::Zilla::Plugin::ReportVersions::Tiny: 1.09
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0.008
  Dist::Zilla::Plugin::Test::Compile: 2.033
  Dist::Zilla::Plugin::Test::Kwalitee: 2.06
  Dist::Zilla::Plugin::Test::MinimumVersion: 2.000005
  Dist::Zilla::Plugin::Test::Perl::Critic: 2.112410
  Dist::Zilla::Plugin::TestRelease: 4.300039
  Dist::Zilla::Plugin::Twitter: 0.021
  Dist::Zilla::Plugin::UploadToCPAN: 4.300039
  Dist::Zilla::Role::FileGatherer: 4.300039
  Dist::Zilla::Role::MintingProfile::ShareDir: 4.300039
  Dist::Zilla::Role::PluginBundle: 4.300039
  Dist::Zilla::Util::EmulatePhase: 0.01025802
  IO::Socket::SSL: 1.954
  LWP::Protocol::https: 6.04
  Moose: 2.1005
  MooseX::Has::Sugar: 0.05070421
  MooseX::Types: 0.38
  Net::SSLeay: 1.55
  Perl::PrereqScanner: 1.016
  Pod::Coverage::TrustPod: 0.100002
  Pod::Weaver::Plugin::Encoding: 0.01
  String::Formatter: 0.102082
  Test::CPAN::Meta: 0.23
  Test::EOL: 1.5
  Test::Perl::Critic: 1.02
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
  namespace::autoclean: 0.13
  perl: v5.10.0
  strict: 0
  version: 0.9904
  warnings: 0
resources:
  bugtracker: https://github.com/kentfredric/Dist-Zilla-PluginBundle-Author-KENTNL/issues
  homepage: https://github.com/kentfredric/Dist-Zilla-PluginBundle-Author-KENTNL
  repository: https://github.com/kentfredric/Dist-Zilla-PluginBundle-Author-KENTNL.git
version: 1.9.0
x_BuiltWith:
  modules:
    Capture::Tiny: 0.22
    Carp: 1.32
    Dist::Zilla: 4.300039
    Dist::Zilla::File::FromCode: 4.300039
    Dist::Zilla::Plugin::Authority: 1.006
    Dist::Zilla::Plugin::Bootstrap::lib: 0.04000001
    Dist::Zilla::Plugin::FakeRelease: 4.300039
    Dist::Zilla::Plugin::MetaProvides: 1.15000000
    Dist::Zilla::Plugin::MinimumPerl: 1.003
    Dist::Zilla::Plugin::PerlTidy: 0.13
    Dist::Zilla::PluginBundle::Author::KENTNL: 1.8.5
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 1.7.2
    Dist::Zilla::Role::FileGatherer: 4.300039
    Dist::Zilla::Role::MintingProfile::ShareDir: 4.300039
    Dist::Zilla::Role::PluginBundle: 4.300039
    Dist::Zilla::Util::EmulatePhase: 0.01025802
    File::Spec: 3.44
    File::pushd: 1.005
    FindBin: 1.51
    Git::Wrapper: 0.030
    IO::Handle: 1.35
    IO::Socket::SSL: 1.954
    IPC::Open3: 1.15
    JSON: 2.59
    LWP::Protocol::https: 6.04
    Module::Build: 0.4007
    Moose: 2.1005
    MooseX::Has::Sugar: 0.05070421
    MooseX::Types: 0.38
    Net::SSLeay: 1.55
    Path::Class: 0.32
    Perl::PrereqScanner: 1.016
    Pod::Coverage::TrustPod: 0.100002
    Pod::Weaver::Plugin::Encoding: 0.01
    String::Formatter: 0.102082
    Test::CPAN::Changes: 0.23
    Test::CPAN::Meta: 0.23
    Test::DZil: 4.300039
    Test::EOL: 1.5
    Test::Fatal: 0.013
    Test::File::ShareDir: 0.3.3
    Test::Kwalitee: 1.15
    Test::More: 0.98
    Test::Output: 1.02
    Test::Perl::Critic: 1.02
    Test::Pod: 1.48
    Test::Pod::Coverage: 1.08
    namespace::autoclean: 0.13
    strict: 1.08
    version: 0.9904
    warnings: 1.18
  perl:
    original: v5.19.3
    qv: 1
    version:
      - 5
      - 19
      - 3
  perl-config:
    gccversion: 4.7.2
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.11.1-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: 5.019003
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          distname: Dist-Zilla-PluginBundle-Author-KENTNL
          fallback: 1
          try_built: 1
          try_built_method: mtime
      name: Bootstrap::lib
      version: 0.04000001
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::KENTNL/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: 0.38
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package: {}
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::KENTNL/MetaProvides::Package'
      version: 1.15000000
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 1
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: 0.04000000
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::KENTNL/Git::GatherDir'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::KENTNL/ReportVersions::Tiny'
      version: 1.09
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: 2.06
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::KENTNL/Test::Compile'
      version: 2.033
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::KENTNL/PruneCruft'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: '@Author::KENTNL/PodWeaver'
      version: 3.102000
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::KENTNL/NextRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/Prereqs/BundleDevelSuggests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/Prereqs/BundleDevelRequires'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl
      name: '@Author::KENTNL/Author::KENTNL::MinimumPerl'
      version: 1.8.5
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::KENTNL/ModuleBuild'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Author::KENTNL/CheckExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_master'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_release'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: 0.021
    -
      class: Dist::Zilla::Plugin::Prereqs::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::MatchInstalled:
          applyto:
            - build.requires
            - build.recommends
            - build.suggests
            - test.requires
            - test.recommends
            - test.suggests
            - runtime.requires
            - runtime.recommends
            - runtime.suggests
            - configure.requires
            - configure.recommends
            - configure.suggests
            - develop.requires
            - develop.recommends
            - develop.suggests
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          applyto_relation:
            - requires
            - recommends
            - suggests
          modules:
            - Module::Build
            - Test::More
            - Dist::Zilla::PluginBundle::Author::KENTNL
      name: '@Author::KENTNL/Prereqs::MatchInstalled'
      version: 0.1.4
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs::Plugins
      config:
        Dist::Zilla::Plugin::Prereqs::Plugins:
          exclude:
            - Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl
          phase: runtime
          relation: requires
      name: Prereqs::Plugins
      version: 0.1.3
    -
      class: Dist::Zilla::Plugin::Prereqs::MatchInstalled::All
      config:
        Dist::Zilla::Plugin::Prereqs::MatchInstalled:
          applyto:
            - build.requires
            - build.recommends
            - build.suggests
            - test.requires
            - test.recommends
            - test.suggests
            - runtime.requires
            - runtime.recommends
            - runtime.suggests
            - configure.requires
            - configure.recommends
            - configure.suggests
            - develop.requires
            - develop.recommends
            - develop.suggests
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          applyto_relation:
            - requires
            - recommends
            - suggests
          modules: []
        Dist::Zilla::Plugin::Prereqs::MatchInstalled::All:
          exclude:
            - Dist::Zilla::Plugin::Authority
            - blib
            - strict
            - warnings
            - FindBin
            - Carp
            - IO::Handle
            - IPC::Open3
            - File::Spec
            - Cwd
          upgrade_perl: ~
      name: Prereqs::MatchInstalled::All
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
x_authority: cpan:KENTNL
